version: '3.3'                 # docker-composeのversionを指定
services:
  db:
    build: ./       # Dockerfileの置き場所を指定
    image: mysql:8.0.22
    restart: always
    environment:
      MYSQL_DATABASE: <%= ENV['DATABASE_NAME'] %>
      MYSQL_USER: <%= ENV['DATABASE_USER'] %>
      MYSQL_PASSWORD: <%= ENV['DATABASE_PASSWORD'] %>
      MYSQL_ROOT_PASSWORD: <%= ENV['DATABASE_ROOT_PASSWORD'] %>
    ports:
      - "3306:3306"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db