default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password # MYSQL_ROOT_PASSWORDと同じにする（後述）
  host: motiva-db # MySQLのコンテナ名と同じにする（後述）

development:
  <<: *default
  database: motiva-db-dev
test:
  <<: *default
  database: motiva-db-test
production:
  <<: *default
  database: motiva-db
  username: <%= ENV['RAILS_DATABASE_USER'] %>
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>